language: elixir
sudo: false
elixir:
  - 1.8
  - 1.7
otp_release:
  - 20.3
  - 18.2.1
before_script:
  - mix deps.get
script: mix test
env:
  - MIX_ENV=test
notifications:
  recipients:
    - travis@coryodaniel.com
jobs:
  include:
    - stage: credo
      script: mix credo
    - stage: dialyzer
      script: mix dialyzer
